onEvent('item.registry', event => {
    event.create('quartz_dust').displayName('碎屑石英颗粒').maxStackSize(256)
    event.create('mixed_stone').displayName('有杂质的石头')
    event.create('stone_alloy').displayName('石头合金')
    event.create('stage1_unlock').displayName('§a节点物品0§r')
    event.create('stage2_unlock').displayName('§a节点物品1§r')
    event.create('pulverizer_unlock').displayName('§a磨粉机核心§r')
    event.create('smelter_unlock').displayName('§a感应炉核心§r')
    event.create('stage3_unlock').displayName('§a节点物品2§r')
    event.create('stage4_unlock').displayName('§a节点物品3§r')
})

onEvent('item.tooltip', tooltip => {
  tooltip.add(['kubejs:stone_alloy'], '§7新一代的安山合金，造价更便宜§m（实际上也没便宜到哪里去）')
  tooltip.add(['kubejs:quartz_dust'], '§7碎屑石英颗粒是击杀僵尸及其变种后掉落的，看起来有不小的用处')
  tooltip.add(['kubejs:rotten_flesh_block'], '§7腐肉做成的方块。这很酷，不是吗？即使硬度不高')
  tooltip.add(['kubejs:garden_soil'], '§7不能种植物？但是能做不少东西')
  tooltip.add(['kubejs:stage1_unlock'], '§9§l可用于解锁阶段1§r')
  tooltip.add(['kubejs:stage2_unlock'], '§9§l可用于解锁阶段2§r')
  tooltip.add(['kubejs:pulverizer_unlock'], '§9§l应用于磨粉机合成中§r')
  tooltip.add(['kubejs:smelter_unlock'], '§9§l应用于感应炉合成中§r')
  tooltip.add(['kubejs:stage3_unlock'], '§9§l可用于解锁阶段3、合成Thermal Series的机器框架§r')
  tooltip.add(['kubejs:cobble_press_2'],'§9§l看起来和普通石头没什么区别§r')
  tooltip.add(['kubejs:cobble_press_3'],'§9§l看起来和普通石头没什么区别§r')
  tooltip.add(['kubejs:cobble_press_4'], '§9§l看起来只剩下了黑色。根据古书记载，将它丢进一个充满蓝色液体的池子后会变成黑曜石§r')
  tooltip.add(['kubejs:blastbrick_wip'], '§9§l表面满是裂纹，根据古籍的记载，它与某些物品一起合成，可以制作高炉砖§r')
})