onEvent('block.registry', event => {
    event.create('garden_soil').material('earth').hardness(1.0).displayName('园艺土')
    event.create('mixed_stone').material('rock').hardness(1.0).displayName('有杂质的石头')
    event.create('rotten_flesh_block').material('earth').hardness(0.25).displayName('压实腐肉块')
    event.create('cobble_press_2').material('rock').hardness(10.0).displayName('§8圆圆石石§r')
    event.create('cobble_press_3').material('rock').hardness(90.0).displayName('§8圆圆圆石石石§r')
    event.create('cobble_press_4').material('rock').hardness(810.0).displayName('§8圆圆圆圆石石石石§r')
    event.create('blastbrick_wip').material('rock').hardness(1.0).displayName('粗制高炉砖')
    event.create('nether_arcane_ore').material('rock').type('basic').hardness(3.0).resistance(3).harvestTool('pickaxe', 2).displayName('下界魔源宝石矿石')
    event.create('nether_diamand_ore').material('rock').type('basic').hardness(3.0).resistance(3).harvestTool('pickaxe', 2).displayName('下界钻石矿石')
    event.create('nether_rock_crystal_ore').material('rock').type('basic').hardness(3.0).resistance(3).harvestTool('pickaxe', 2).displayName('下界水晶石矿石')
    event.create('nether_starmetal_ore').material('rock').type('basic').hardness(3.0).resistance(3).harvestTool('pickaxe', 2).displayName('下界星辉矿石')
    event.create('nether_zinc_ore').material('rock').type('basic').hardness(3.0).resistance(3).harvestTool('pickaxe', 2).displayName('下界锌矿石')
    event.create('nether_uranium_ore').material('rock').type('basic').hardness(3.0).resistance(3).harvestTool('pickaxe', 2).displayName('下界铀矿石')
    event.create('nether_fluorite_ore').material('rock').type('basic').hardness(3.0).resistance(3).harvestTool('pickaxe', 2).displayName('下界氟石矿石')
    event.create('nether_nickle_ore').material('rock').type('basic').hardness(3.0).resistance(3).harvestTool('pickaxe', 2).displayName('下界镍矿石')
    event.create('nether_silver_ore').material('rock').type('basic').hardness(3.0).resistance(3).harvestTool('pickaxe', 2).displayName('下界银矿石')
})